import 'dotenv/config';
import express from 'express';
import Database from 'better-sqlite3';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import cookieParser from 'cookie-parser';
import multer from 'multer';
import * as XLSX from 'xlsx';
import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const databasePath = path.resolve(process.env.DATABASE_PATH || path.join(root, 'data', 'shipments.db'));
const uploadPath = path.resolve(process.env.UPLOAD_DIR || path.join(root, 'uploads'));
fs.mkdirSync(path.dirname(databasePath), { recursive: true });
fs.mkdirSync(uploadPath, { recursive: true });
const db = new Database(databasePath);
db.pragma('journal_mode = WAL');
db.exec(`CREATE TABLE IF NOT EXISTS shipments (
 id INTEGER PRIMARY KEY AUTOINCREMENT, sl_no TEXT, qfz_ref TEXT UNIQUE, packing_list TEXT, brand TEXT,
 pl_received_date TEXT, pl_received_time TEXT, metrology_documents_received TEXT,
 attestation_date TEXT, attestation_time TEXT, bayan_received_date TEXT, bayan_received_time TEXT,
 payment_confirmation_date TEXT, payment_confirmation_time TEXT, metrology_approval_date TEXT, metrology_approval_time TEXT,
 dispatched_date TEXT, dispatched_time TEXT, remarks TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP, updated_at TEXT DEFAULT CURRENT_TIMESTAMP
); CREATE INDEX IF NOT EXISTS idx_shipments_ref ON shipments(qfz_ref);`);

const fields = ['sl_no','qfz_ref','packing_list','brand','pl_received_date','pl_received_time','metrology_documents_received','attestation_date','attestation_time','bayan_received_date','bayan_received_time','payment_confirmation_date','payment_confirmation_time','metrology_approval_date','metrology_approval_time','dispatched_date','dispatched_time','remarks'];
const production = process.env.NODE_ENV === 'production';
const secret = process.env.SESSION_SECRET || (production ? '' : 'local-development-secret-change-me');
const adminUser = process.env.ADMIN_USERNAME || 'admin';
const adminPassword = process.env.ADMIN_PASSWORD || 'change-this-password';
const adminPasswordHash = process.env.ADMIN_PASSWORD_HASH || '';
if (production && (secret.length < 32 || !adminPasswordHash.startsWith('$2'))) throw new Error('Production requires a 32+ character SESSION_SECRET and bcrypt ADMIN_PASSWORD_HASH.');
const app = express();
if (production) app.set('trust proxy', 1);
app.disable('x-powered-by');
app.use((_,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');res.setHeader('Cross-Origin-Resource-Policy','same-origin');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'");if(production)res.setHeader('Strict-Transport-Security','max-age=31536000; includeSubDomains');next();});
app.use(express.json({limit:'100kb'})); app.use(cookieParser());
const upload = multer({ dest:uploadPath, limits:{fileSize:5*1024*1024,files:1}, fileFilter:(_,file,cb)=>cb(null,file.originalname.toLowerCase().endsWith('.xlsx')&&['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/octet-stream',''].includes(file.mimetype)) });
const auth: express.RequestHandler = (req,res,next) => { try { const t=req.cookies.qfz_admin; if(!t) throw 0; jwt.verify(t,secret,{algorithms:['HS256']}); next(); } catch { res.status(401).json({error:'Admin authentication required.'}); } };
const attempts=new Map<string,{count:number,reset:number}>();
const rateLimitLogin: express.RequestHandler=(req,res,next)=>{const ip=req.ip||req.socket.remoteAddress||'unknown',now=Date.now(),entry=attempts.get(ip);if(!entry||entry.reset<now)attempts.set(ip,{count:1,reset:now+900000});else entry.count++;if((attempts.get(ip)?.count||0)>8)return res.status(429).json({error:'Too many login attempts. Try again in 15 minutes.'});next();};
const sameOrigin: express.RequestHandler=(req,res,next)=>{const origin=req.get('origin');if(!origin)return next();try{if(new URL(origin).host!==req.get('host'))return res.status(403).json({error:'Request origin is not allowed.'});next();}catch{return res.status(403).json({error:'Request origin is not allowed.'});}};
function stamp(d?:string,t?:string) { if (!d) return null; const s=`${d}${t?`T${t.length===5?t+':00':t}`:'T00:00:00'}`; const x=new Date(s); return Number.isNaN(+x)?null:x; }
function duration(d?:string,t?:string,endD?:string,endT?:string) { const a=stamp(d,t), b=stamp(endD,endT); if(!a||!b) return null; const ms=+b-+a; if(ms<0) return 'Invalid dates'; const mins=Math.round(ms/60000), days=Math.floor(mins/1440), hrs=Math.floor((mins%1440)/60), rem=mins%60; return [days&&`${days} Days`,hrs&&`${hrs} Hrs`,rem&&`${rem} Mins`].filter(Boolean).join(' ') || '0 Hrs'; }
function enriched(row:any) { return {...row, status:row.dispatched_date?'Dispatched':'In Progress', attestation_duration:duration(row.pl_received_date,row.pl_received_time,row.attestation_date,row.attestation_time), total_dispatch_duration:duration(row.pl_received_date,row.pl_received_time,row.dispatched_date,row.dispatched_time)}; }
function valid(x:any) { if(!x.qfz_ref?.trim()||!x.packing_list?.trim()||!x.pl_received_date) return 'QFZ Ref, Packing List and PL Received date are required.'; for(const k of ['pl_received_date','attestation_date','bayan_received_date','payment_confirmation_date','metrology_approval_date','dispatched_date']) if(x[k]&&!/^\d{4}-\d{2}-\d{2}$/.test(x[k])) return `Invalid ${k}. Use YYYY-MM-DD.`; for(const k of ['pl_received_time','attestation_time','bayan_received_time','payment_confirmation_time','metrology_approval_time','dispatched_time']) if(x[k]&&!/^\d{2}:\d{2}$/.test(x[k])) return `Invalid ${k}. Use HH:MM.`; for(const [a,b] of [['attestation_date','attestation_time'],['dispatched_date','dispatched_time']] as const) { const z=duration(x.pl_received_date,x.pl_received_time,x[a],x[b]); if(z==='Invalid dates') return `${a} cannot be before PL Received.`; } return null; }
function clean(body:any) { const out:any={}; fields.forEach(f=>out[f]=typeof body[f]==='string'?body[f].replace(/[\u0000-\u001F\u007F]/g,'').trim().slice(0,1000):body[f]??''); return out; }
app.get('/api/shipments',(_,res)=>res.json(db.prepare('SELECT * FROM shipments ORDER BY id DESC').all().map(enriched)));
app.get('/api/health',(_,res)=>{try{db.prepare('SELECT 1').get();res.json({ok:true});}catch{res.status(503).json({ok:false});}});
app.get('/api/shipments/:id',(req,res)=>{const x=db.prepare('SELECT * FROM shipments WHERE id=?').get(req.params.id); x?res.json(enriched(x)):res.status(404).json({error:'Shipment not found.'});});
app.post('/api/admin/login',sameOrigin,rateLimitLogin,async(req,res)=> { if(typeof req.body?.username!=='string'||typeof req.body?.password!=='string'||req.body.username.length>100||req.body.password.length>200)return res.status(400).json({error:'Invalid login request.'}); const expectedHash=adminPasswordHash||await bcrypt.hash(adminPassword,10); if(req.body.username!==adminUser || !(await bcrypt.compare(req.body.password,expectedHash))) return res.status(401).json({error:'Invalid username or password.'}); attempts.delete(req.ip||req.socket.remoteAddress||'unknown'); const token=jwt.sign({role:'admin'},secret,{algorithm:'HS256',expiresIn:'8h'}); res.cookie('qfz_admin',token,{httpOnly:true,sameSite:'lax',secure:production,maxAge:28800000,path:'/'}); res.json({username:adminUser}); });
app.post('/api/admin/logout',auth,sameOrigin,(_,res)=>{res.clearCookie('qfz_admin',{httpOnly:true,sameSite:'lax',secure:production,path:'/'});res.json({ok:true});}); app.get('/api/admin/me',(req,res)=>{try{jwt.verify(req.cookies.qfz_admin,secret,{algorithms:['HS256']});res.json({username:adminUser});}catch{res.status(401).json({error:'Not signed in'});}});
app.post('/api/shipments',auth,sameOrigin,(req,res)=> { const x=clean(req.body), e=valid(x); if(e)return res.status(400).json({error:e}); try { const q=`INSERT INTO shipments (${fields.join(',')}) VALUES (${fields.map(()=>'?').join(',')})`; const info=db.prepare(q).run(...fields.map(f=>x[f])); res.status(201).json(enriched(db.prepare('SELECT * FROM shipments WHERE id=?').get(info.lastInsertRowid))); }catch(err:any){res.status(400).json({error:err.message.includes('UNIQUE')?'QFZ Ref must be unique.':'Could not save shipment.'});}});
app.put('/api/shipments/:id',auth,sameOrigin,(req,res)=> {const x=clean(req.body),e=valid(x);if(e)return res.status(400).json({error:e});try{const q=`UPDATE shipments SET ${fields.map(f=>`${f}=?`).join(',')}, updated_at=CURRENT_TIMESTAMP WHERE id=?`;if(!db.prepare(q).run(...fields.map(f=>x[f]),req.params.id).changes)return res.status(404).json({error:'Shipment not found.'});res.json(enriched(db.prepare('SELECT * FROM shipments WHERE id=?').get(req.params.id)));}catch(err:any){res.status(400).json({error:err.message.includes('UNIQUE')?'QFZ Ref must be unique.':'Could not save shipment.'});}});
app.delete('/api/shipments/:id',auth,sameOrigin,(req,res)=>{if(!db.prepare('DELETE FROM shipments WHERE id=?').run(req.params.id).changes)return res.status(404).json({error:'Shipment not found.'});res.json({ok:true});});
function excelDate(v:any){ if(v instanceof Date)return `${v.getFullYear()}-${String(v.getMonth()+1).padStart(2,'0')}-${String(v.getDate()).padStart(2,'0')}`; if(typeof v==='number'){const d=XLSX.SSF.parse_date_code(v);return d?`${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`:''} const m=String(v||'').match(/(\d{1,2})[\/-]([A-Za-z]{3}|\d{1,2})[\/-](\d{2,4})/); if(!m)return ''; let mo=/[A-Za-z]/.test(m[2])?['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'].indexOf(m[2].toUpperCase())+1:+m[2],y=+m[3];if(y<100)y+=2000; return mo?`${y}-${String(mo).padStart(2,'0')}-${String(+m[1]).padStart(2,'0')}`:'';}
function excelTime(v:any){if(v instanceof Date)return `${String(v.getHours()).padStart(2,'0')}:${String(v.getMinutes()).padStart(2,'0')}`;const s=String(v??'').trim().replace(/\s/g,'');if(!s)return ''; const m=s.match(/(\d{1,2}):(\d{2})(?::\d{2})?(AM|PM)?/i);if(!m)return '';let h=+m[1];if(m[3]){if(h===12)h=0;if(m[3].toUpperCase()==='PM')h+=12}return `${String(h).padStart(2,'0')}:${m[2]}`;}
function mapped(sheet:XLSX.WorkSheet){
 // Use Excel's displayed value where available: its Date objects can be UTC-shifted,
 // whereas `w` preserves the spreadsheet's intended local business date/time.
 const cell=(col:string,row:number)=>sheet[`${col}${row}`]?.w ?? sheet[`${col}${row}`]?.v ?? '';
 if(String(cell('B',1)).toUpperCase().includes('QFZ REF')) { const end=XLSX.utils.decode_range(sheet['!ref']||'A1').e.r+1, out:any[]=[]; for(let r=3;r<=end;r++) { const qfz=String(cell('B',r)).trim(); if(!qfz||!/^QFZ/i.test(qfz))continue; out.push(clean({sl_no:String(cell('A',r)),qfz_ref:qfz,packing_list:String(cell('C',r)),brand:String(cell('D',r)),pl_received_date:excelDate(cell('E',r)),pl_received_time:excelTime(cell('F',r)),metrology_documents_received:String(cell('H',r)),attestation_date:excelDate(cell('I',r)),attestation_time:excelTime(cell('J',r)),bayan_received_date:excelDate(cell('M',r)),bayan_received_time:excelTime(cell('N',r)),payment_confirmation_date:excelDate(cell('Q',r)),payment_confirmation_time:excelTime(cell('R',r)),metrology_approval_date:excelDate(cell('U',r)),metrology_approval_time:excelTime(cell('V',r)),dispatched_date:excelDate(cell('X',r)),dispatched_time:excelTime(cell('Y',r)),remarks:String(cell('AB',r))})); } return out;
 }
 const rows=XLSX.utils.sheet_to_json<any>(sheet,{defval:'',raw:false});return rows.map(r=>{const find=(...keys:string[])=>{const k=Object.keys(r).find(x=>keys.some(y=>x.toLowerCase().replace(/\s+/g,' ').includes(y)));return k?r[k]:''};return clean({sl_no:find('sl no'),qfz_ref:find('qfz ref'),packing_list:find('packing list'),brand:find('brand'),pl_received_date:excelDate(find('pl received from wh date','pl received date')),pl_received_time:excelTime(find('pl received from wh time','pl received time')),metrology_documents_received:find('metrology shipment','metrology documents'),attestation_date:excelDate(find('apply for attestation date')),attestation_time:excelTime(find('apply for attestation time')),bayan_received_date:excelDate(find('bayan received date')),bayan_received_time:excelTime(find('bayan received time')),payment_confirmation_date:excelDate(find('payment confirmation from wh date')),payment_confirmation_time:excelTime(find('payment confirmation from wh time')),metrology_approval_date:excelDate(find('metrology approval date')),metrology_approval_time:excelTime(find('metrology approval time')),dispatched_date:excelDate(find('disptached date','dispatched date')),dispatched_time:excelTime(find('disptached time','dispatched time')),remarks:find('remarks')});}).filter(x=>x.qfz_ref||x.packing_list);}
function seedDatabaseIfEmpty(){const count=(db.prepare('SELECT COUNT(*) AS count FROM shipments').get()as any).count;if(count)return;const workbookPath=process.env.SEED_WORKBOOK_PATH||path.join(root,'source','Tracker for Aug 2026 - QFZ outbound shipments.xlsx');if(!fs.existsSync(workbookPath))return;try{const wb=XLSX.readFile(workbookPath,{cellDates:true}),rows=mapped(wb.Sheets[wb.SheetNames[0]]);const insert=db.prepare(`INSERT OR IGNORE INTO shipments (${fields.join(',')}) VALUES (${fields.map(()=>'?').join(',')})`);db.transaction(()=>rows.forEach(x=>{if(!valid(x))insert.run(...fields.map(f=>x[f]));}))();console.log(`Seeded ${rows.length} shipment rows into ${databasePath}`);}catch{console.warn('Database is empty; workbook seed was not applied. Use the Admin Excel import after startup.');}}
seedDatabaseIfEmpty();
app.post('/api/import',auth,sameOrigin,upload.single('file'),(req,res)=>{try{if(!req.file||!req.file.originalname.toLowerCase().endsWith('.xlsx'))throw Error('Please choose an .xlsx file.');const buf=fs.readFileSync(req.file.path);if(buf.length<4||buf.subarray(0,2).toString()!=='PK')throw Error('Invalid Excel file.');const wb=XLSX.read(buf,{type:'buffer',cellDates:true});if(!wb.SheetNames.length||wb.SheetNames.length>10)throw Error('Invalid Excel workbook.');const sheet=wb.Sheets[wb.SheetNames[0]],range=XLSX.utils.decode_range(sheet['!ref']||'A1');if(range.e.r>5000||range.e.c>100)throw Error('Workbook exceeds supported size.');const rows=mapped(sheet);let imported=0,updated=0,skipped=0,errors=0;const tx=db.transaction(()=>rows.forEach(x=>{const e=valid(x);if(e){errors++;return}const old=db.prepare('SELECT id FROM shipments WHERE qfz_ref=?').get(x.qfz_ref)as any;if(old){db.prepare(`UPDATE shipments SET ${fields.map(f=>`${f}=?`).join(',')},updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(...fields.map(f=>x[f]),old.id);updated++;}else{db.prepare(`INSERT INTO shipments (${fields.join(',')}) VALUES (${fields.map(()=>'?').join(',')})`).run(...fields.map(f=>x[f]));imported++;}}));tx();fs.unlinkSync(req.file.path);res.json({imported,updated,skipped,errors,total:rows.length,sheet:wb.SheetNames[0]});}catch(e:any){if(req.file&&fs.existsSync(req.file.path))fs.unlinkSync(req.file.path);res.status(400).json({error:'Could not import workbook.'});}});
app.get('/api/export',auth,(_,res)=>{try{const rows=db.prepare('SELECT * FROM shipments ORDER BY id').all().map(enriched);const data=rows.map((x:any)=>({'SL NO':x.sl_no,'QFZ Ref':x.qfz_ref,'Packing List':x.packing_list,'Brand':x.brand,'PL Received Date':x.pl_received_date,'PL Received Time':x.pl_received_time,'Metrology Documents Received':x.metrology_documents_received,'Apply for Attestation Date':x.attestation_date,'Apply for Attestation Time':x.attestation_time,'Bayan Received Date':x.bayan_received_date,'Bayan Received Time':x.bayan_received_time,'Payment Confirmation Date':x.payment_confirmation_date,'Payment Confirmation Time':x.payment_confirmation_time,'Metrology Approval Date':x.metrology_approval_date,'Metrology Approval Time':x.metrology_approval_time,'Dispatched Date':x.dispatched_date,'Dispatched Time':x.dispatched_time,'Attestation Duration':x.attestation_duration||'','Total Dispatch Duration':x.total_dispatch_duration||'','Status':x.status,'Remarks':x.remarks}));const ws=XLSX.utils.json_to_sheet(data);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Shipments');const buf=XLSX.write(wb,{type:'buffer',bookType:'xlsx'});res.setHeader('Content-Disposition','attachment; filename="qfz-shipments.xlsx"');res.type('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet').send(buf);}catch{res.status(500).json({error:'Could not export shipments.'});}});
if(process.env.NODE_ENV==='production'){app.use(express.static(path.join(root,'dist')));app.get('*',(_,res)=>res.sendFile(path.join(root,'dist','index.html')))}
app.use((err:any,_:express.Request,res:express.Response,_next:express.NextFunction)=>{if(err instanceof multer.MulterError)return res.status(400).json({error:err.code==='LIMIT_FILE_SIZE'?'Excel file must be 5 MB or smaller.':'Invalid file upload.'});res.status(400).json({error:'Invalid request.'});});
app.listen(Number(process.env.PORT)||3001,'0.0.0.0',()=>console.log('QFZ server running on port '+(process.env.PORT||3001)));
