import 'dotenv/config';
import express from 'express';
import Database from 'better-sqlite3';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import cookieParser from 'cookie-parser';
import multer from 'multer';
import * as XLSX from 'xlsx';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const root = process.cwd();
const databasePath = path.resolve(process.env.DATABASE_PATH || path.join(root, 'data', 'shipments.db'));
const uploadPath = path.resolve(process.env.UPLOAD_DIR || path.join(root, 'uploads'));
fs.mkdirSync(path.dirname(databasePath), { recursive: true });
fs.mkdirSync(uploadPath, { recursive: true });
const db = new Database(databasePath);
db.pragma('journal_mode = WAL');
db.exec(`CREATE TABLE IF NOT EXISTS shipments (
 id INTEGER PRIMARY KEY AUTOINCREMENT, sl_no TEXT, qfz_ref TEXT UNIQUE, packing_list TEXT, brand TEXT,
 pl_received_date TEXT, pl_received_time TEXT, metrology_documents_received TEXT,
 attestation_date TEXT, attestation_time TEXT, bayan_received_date TEXT, bayan_received_time TEXT,
 payment_confirmation_date TEXT, payment_confirmation_time TEXT, metrology_approval_date TEXT, metrology_approval_time TEXT,
 dispatched_date TEXT, dispatched_time TEXT, remarks TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP, updated_at TEXT DEFAULT CURRENT_TIMESTAMP
); CREATE INDEX IF NOT EXISTS idx_shipments_ref ON shipments(qfz_ref);`);
db.exec(`CREATE TABLE IF NOT EXISTS app_config (key TEXT PRIMARY KEY, value TEXT NOT NULL);`);

const fields = ['sl_no','qfz_ref','packing_list','brand','pl_received_date','pl_received_time','metrology_documents_received','attestation_date','attestation_time','bayan_received_date','bayan_received_time','payment_confirmation_date','payment_confirmation_time','metrology_approval_date','metrology_approval_time','dispatched_date','dispatched_time','remarks'];
const production = process.env.NODE_ENV === 'production';
const adminUser = process.env.ADMIN_USERNAME?.trim() || 'admin';
const configValue=(key:string)=>db.prepare('SELECT value FROM app_config WHERE key=?').get(key) as {value:string}|undefined;
const saveConfig=(key:string,value:string)=>db.prepare('INSERT OR IGNORE INTO app_config (key,value) VALUES (?,?)').run(key,value);
const storedSecret=configValue('session_secret')?.value;
const secret=process.env.SESSION_SECRET || storedSecret || crypto.randomBytes(48).toString('base64url');
if(!process.env.SESSION_SECRET&&!storedSecret)saveConfig('session_secret',secret);
// Read the plain password only from the host environment and turn it into a
// bcrypt hash in memory. This intentionally ignores legacy hash variables so
// an outdated Render value cannot block the documented admin login.
const defaultAdminPasswordHash='$2a$12$WeRUJlDox0FB1J14wPwHx.mh9GR.i079SlCzi4axnGMC6rfnK5rRe';
const adminPasswordHash=process.env.ADMIN_PASSWORD ? bcrypt.hashSync(process.env.ADMIN_PASSWORD,12) : defaultAdminPasswordHash;
const app = express();
if (production) app.set('trust proxy', 1);
app.disable('x-powered-by');
app.use((_,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');res.setHeader('Cross-Origin-Resource-Policy','same-origin');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'");if(production)res.setHeader('Strict-Transport-Security','max-age=31536000; includeSubDomains');next();});
app.use(express.json({limit:'100kb'})); app.use(cookieParser());
const upload = multer({ dest:uploadPath, limits:{fileSize:5*1024*1024,files:1}, fileFilter:(_,file,cb)=>cb(null,file.originalname.toLowerCase().endsWith('.xlsx')&&['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/octet-stream',''].includes(file.mimetype)) });
const auth: express.RequestHandler = (req,res,next) => { try { const t=req.cookies.qfz_admin; if(!t) throw 0; jwt.verify(t,secret,{algorithms:['HS256']}); next(); } catch { res.status(401).json({error:'Admin authentication required.'}); } };
const attempts=new Map<string,{count:number,reset:number}>();
const rateLimitLogin: express.RequestHandler=(req,res,next)=>{const ip=req.ip||req.socket.remoteAddress||'unknown',now=Date.now(),entry=attempts.get(ip);if(!entry||entry.reset<now)attempts.set(ip,{count:1,reset:now+900000});else entry.count++;if((attempts.get(ip)?.count||0)>8)return res.status(429).json({error:'Too many login attempts. Try again in 15 minutes.'});next();};
const sameOrigin: express.RequestHandler=(req,res,next)=>{const origin=req.get('origin');if(!origin)return next();try{if(new URL(origin).host!==req.get('host'))return res.status(403).json({error:'Request origin is not allowed.'});next();}catch{return res.status(403).json({error:'Request origin is not allowed.'});}};
function stamp(d?:string,t?:string) { if (!d) return null; const s=`${d}${t?`T${t.length===5?t+':00':t}`:'T00:00:00'}`; const x=new Date(s); return Number.isNaN(+x)?null:x; }
function duration(d?:string,t?:string,endD?:string,endT?:string) { const a=stamp(d,t), b=stamp(endD,endT); if(!a||!b) return null; const ms=+b-+a; if(ms<0) return 'Invalid dates'; const mins=Math.round(ms/60000), days=Math.floor(mins/1440), hrs=Math.floor((mins%1440)/60), rem=mins%60; return [days&&`${days} Days`,hrs&&`${hrs} Hrs`,rem&&`${rem} Mins`].filter(Boolean).join(' ') || '0 Hrs'; }
// The workbook has no explicit delayed flag or SLA. By default, derive the
// expected dispatch time from the 75th percentile of completed tracker rows.
// A host can set DELAY_SLA_HOURS to an agreed business SLA without changing code.
const delayPercentile=0.75;
function percentile(values:number[], p:number) { if(!values.length)return 48; const sorted=[...values].sort((a,b)=>a-b), index=(sorted.length-1)*p, lower=Math.floor(index), upper=Math.ceil(index); return lower===upper?sorted[lower]:sorted[lower]+(sorted[upper]-sorted[lower])*(index-lower); }
function delayThresholdHours() { const configured=Number(process.env.DELAY_SLA_HOURS); if(Number.isFinite(configured)&&configured>0)return configured; const values=(db.prepare('SELECT pl_received_date,pl_received_time,dispatched_date,dispatched_time FROM shipments WHERE dispatched_date IS NOT NULL').all() as any[]).map(row=>{const start=stamp(row.pl_received_date,row.pl_received_time),end=stamp(row.dispatched_date,row.dispatched_time);return start&&end&&end>=start?(+end-+start)/3600000:null}).filter((value):value is number=>value!==null); return percentile(values,delayPercentile); }
function delayInfo(row:any, thresholdHours:number) { const start=stamp(row.pl_received_date,row.pl_received_time); if(row.dispatched_date||!start)return {is_delayed:false,delay_reason:'',delay_threshold_hours:thresholdHours}; const elapsed=(Date.now()-+start)/3600000; if(elapsed<=thresholdHours)return {is_delayed:false,delay_reason:'',delay_threshold_hours:thresholdHours}; const elapsedHours=Math.max(1,Math.round(elapsed)), overdue=Math.max(1,Math.round(elapsed-thresholdHours)); return {is_delayed:true,delay_reason:`PL received ${elapsedHours} hours ago — dispatched date is still missing (${overdue} hour${overdue===1?'':'s'} beyond the expected timeline).`,delay_threshold_hours:thresholdHours}; }
function enriched(row:any, thresholdHours=delayThresholdHours()) { return {...row, status:row.dispatched_date?'Dispatched':'In Progress', attestation_duration:duration(row.pl_received_date,row.pl_received_time,row.attestation_date,row.attestation_time), total_dispatch_duration:duration(row.pl_received_date,row.pl_received_time,row.dispatched_date,row.dispatched_time), ...delayInfo(row,thresholdHours)}; }
function enrichRows(rows:any[]) { const thresholdHours=delayThresholdHours(); return rows.map(row=>enriched(row,thresholdHours)); }
function valid(x:any) { if(!x.qfz_ref?.trim()||!x.packing_list?.trim()||!x.pl_received_date) return 'QFZ Ref, Packing List and PL Received date are required.'; for(const k of ['pl_received_date','attestation_date','bayan_received_date','payment_confirmation_date','metrology_approval_date','dispatched_date']) if(x[k]&&!/^\d{4}-\d{2}-\d{2}$/.test(x[k])) return `Invalid ${k}. Use YYYY-MM-DD.`; for(const k of ['pl_received_time','attestation_time','bayan_received_time','payment_confirmation_time','metrology_approval_time','dispatched_time']) if(x[k]&&!/^\d{2}:\d{2}$/.test(x[k])) return `Invalid ${k}. Use HH:MM.`; for(const [a,b] of [['attestation_date','attestation_time'],['dispatched_date','dispatched_time']] as const) { const z=duration(x.pl_received_date,x.pl_received_time,x[a],x[b]); if(z==='Invalid dates') return `${a} cannot be before PL Received.`; } return null; }
function clean(body:any) { const out:any={}; fields.forEach(f=>out[f]=typeof body[f]==='string'?body[f].replace(/[\u0000-\u001F\u007F]/g,'').trim().slice(0,1000):body[f]??''); return out; }
app.get('/api/shipments',(_,res)=>res.json(enrichRows(db.prepare('SELECT * FROM shipments ORDER BY id DESC').all() as any[])));
app.get('/api/health',(_,res)=>{try{db.prepare('SELECT 1').get();res.json({ok:true});}catch{res.status(503).json({ok:false});}});
app.get('/api/shipments/:id',(req,res)=>{const x=db.prepare('SELECT * FROM shipments WHERE id=?').get(req.params.id); x?res.json(enriched(x)):res.status(404).json({error:'Shipment not found.'});});
app.post('/api/admin/login',sameOrigin,rateLimitLogin,async(req,res)=> { if(typeof req.body?.username!=='string'||typeof req.body?.password!=='string'||req.body.username.length>100||req.body.password.length>200)return res.status(400).json({error:'Invalid login request.'}); if(req.body.username!==adminUser || !(await bcrypt.compare(req.body.password,adminPasswordHash))) return res.status(401).json({error:'Invalid username or password.'}); attempts.delete(req.ip||req.socket.remoteAddress||'unknown'); const token=jwt.sign({role:'admin'},secret,{algorithm:'HS256',expiresIn:'8h'}); res.cookie('qfz_admin',token,{httpOnly:true,sameSite:'lax',secure:production,maxAge:28800000,path:'/'}); res.json({username:adminUser}); });
app.post('/api/admin/logout',auth,sameOrigin,(_,res)=>{res.clearCookie('qfz_admin',{httpOnly:true,sameSite:'lax',secure:production,path:'/'});res.json({ok:true});}); app.get('/api/admin/me',(req,res)=>{try{jwt.verify(req.cookies.qfz_admin,secret,{algorithms:['HS256']});res.json({username:adminUser});}catch{res.status(401).json({error:'Not signed in'});}});
app.post('/api/shipments',auth,sameOrigin,(req,res)=> { const x=clean(req.body), e=valid(x); if(e)return res.status(400).json({error:e}); try { const q=`INSERT INTO shipments (${fields.join(',')}) VALUES (${fields.map(()=>'?').join(',')})`; const info=db.prepare(q).run(...fields.map(f=>x[f])); res.status(201).json(enriched(db.prepare('SELECT * FROM shipments WHERE id=?').get(info.lastInsertRowid))); }catch(err:any){res.status(400).json({error:err.message.includes('UNIQUE')?'QFZ Ref must be unique.':'Could not save shipment.'});}});
app.put('/api/shipments/:id',auth,sameOrigin,(req,res)=> {const x=clean(req.body),e=valid(x);if(e)return res.status(400).json({error:e});try{const q=`UPDATE shipments SET ${fields.map(f=>`${f}=?`).join(',')}, updated_at=CURRENT_TIMESTAMP WHERE id=?`;if(!db.prepare(q).run(...fields.map(f=>x[f]),req.params.id).changes)return res.status(404).json({error:'Shipment not found.'});res.json(enriched(db.prepare('SELECT * FROM shipments WHERE id=?').get(req.params.id)));}catch(err:any){res.status(400).json({error:err.message.includes('UNIQUE')?'QFZ Ref must be unique.':'Could not save shipment.'});}});
app.delete('/api/shipments/:id',auth,sameOrigin,(req,res)=>{if(!db.prepare('DELETE FROM shipments WHERE id=?').run(req.params.id).changes)return res.status(404).json({error:'Shipment not found.'});res.json({ok:true});});
function excelDate(v:any){ if(v instanceof Date)return `${v.getFullYear()}-${String(v.getMonth()+1).padStart(2,'0')}-${String(v.getDate()).padStart(2,'0')}`; if(typeof v==='number'){const d=XLSX.SSF.parse_date_code(v);return d?`${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`:''} const m=String(v||'').match(/(\d{1,2})[\/-]([A-Za-z]{3}|\d{1,2})[\/-](\d{2,4})/); if(!m)return ''; let mo=/[A-Za-z]/.test(m[2])?['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'].indexOf(m[2].toUpperCase())+1:+m[2],y=+m[3];if(y<100)y+=2000; return mo?`${y}-${String(mo).padStart(2,'0')}-${String(+m[1]).padStart(2,'0')}`:'';}
function excelTime(v:any){if(v instanceof Date)return `${String(v.getHours()).padStart(2,'0')}:${String(v.getMinutes()).padStart(2,'0')}`;const s=String(v??'').trim().replace(/\s/g,'');if(!s)return ''; const m=s.match(/(\d{1,2}):(\d{2})(?::\d{2})?(AM|PM)?/i);if(!m)return '';let h=+m[1];if(m[3]){if(h===12)h=0;if(m[3].toUpperCase()==='PM')h+=12}return `${String(h).padStart(2,'0')}:${m[2]}`;}
function mapped(sheet:XLSX.WorkSheet){
 // Locate fields from the header row so later tracker versions can insert
 // operational columns (such as duty-paid details) without shifting data.
 const range=XLSX.utils.decode_range(sheet['!ref']||'A1');
 const display=(column:number,row:number)=>sheet[`${XLSX.utils.encode_col(column)}${row}`]?.w ?? sheet[`${XLSX.utils.encode_col(column)}${row}`]?.v ?? '';
 const header=(column:number)=>String(display(column,1)).toLowerCase().replace(/\s+/g,' ').trim();
 const column=(...terms:string[])=>{const index=Array.from({length:range.e.c+1},(_,i)=>i).find(i=>terms.some(term=>header(i).includes(term)));return index===undefined?-1:index};
 const value=(column:number,row:number)=>column<0?'':display(column,row);
 const qfz=column('qfz ref'), packing=column('packing list'), brand=column('brand'), pl=column('pl received from wh'), docs=column('metrology shipment'), attestation=column('apply for attest'), bayan=column('bayan received'), payment=column('payment confirmation from wh'), approval=column('metrology approval'), dispatched=column('disptached date','dispatched date'), remarks=column('remarks'), slNo=column('sl no');
 if(qfz<0)return [];
 const out:any[]=[];
 for(let row=3;row<=range.e.r+1;row++){const reference=String(value(qfz,row)).trim();if(!/^QFZ/i.test(reference))continue;out.push(clean({sl_no:String(value(slNo,row)),qfz_ref:reference,packing_list:String(value(packing,row)),brand:String(value(brand,row)),pl_received_date:excelDate(value(pl,row)),pl_received_time:excelTime(value(pl+1,row)),metrology_documents_received:String(value(docs,row)),attestation_date:excelDate(value(attestation,row)),attestation_time:excelTime(value(attestation+1,row)),bayan_received_date:excelDate(value(bayan,row)),bayan_received_time:excelTime(value(bayan+1,row)),payment_confirmation_date:excelDate(value(payment,row)),payment_confirmation_time:excelTime(value(payment+1,row)),metrology_approval_date:excelDate(value(approval,row)),metrology_approval_time:excelTime(value(approval+1,row)),dispatched_date:excelDate(value(dispatched,row)),dispatched_time:excelTime(value(dispatched+1,row)),remarks:String(value(remarks,row))}));}
 return out;
}
function seedDatabaseIfEmpty(){const workbookPath=process.env.SEED_WORKBOOK_PATH||path.join(root,'source','Tracker for Aug 2026 - QFZ outbound shipments.xlsx');if(!fs.existsSync(workbookPath))return;try{const workbookBytes=fs.readFileSync(workbookPath),workbookHash=crypto.createHash('sha256').update(workbookBytes).digest('hex'),previousHash=configValue('seed_workbook_hash')?.value;if(previousHash===workbookHash)return;const wb=XLSX.read(workbookBytes,{type:'buffer',cellDates:true}),rows=mapped(wb.Sheets[wb.SheetNames[0]]),upsert=db.prepare(`INSERT INTO shipments (${fields.join(',')}) VALUES (${fields.map(()=>'?').join(',')}) ON CONFLICT(qfz_ref) DO UPDATE SET ${fields.filter(f=>f!=='qfz_ref').map(f=>`${f}=excluded.${f}`).join(',')},updated_at=CURRENT_TIMESTAMP`),existingRefs=new Set((db.prepare('SELECT qfz_ref FROM shipments').all() as {qfz_ref:string}[]).map(row=>row.qfz_ref));let imported=0,updated=0;db.transaction(()=>rows.forEach(x=>{if(valid(x))return;existingRefs.has(x.qfz_ref)?updated++:imported++;upsert.run(...fields.map(f=>x[f]));}))();db.prepare('INSERT INTO app_config (key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run('seed_workbook_hash',workbookHash);console.log(`Synced ${rows.length} tracker rows into ${databasePath} (${imported} added, ${updated} updated)`);}catch{console.warn('Tracker workbook sync was not applied. Use the Admin Excel import after startup.');}}
seedDatabaseIfEmpty();
app.post('/api/import',auth,sameOrigin,upload.single('file'),(req,res)=>{try{if(!req.file||!req.file.originalname.toLowerCase().endsWith('.xlsx'))throw Error('Please choose an .xlsx file.');const buf=fs.readFileSync(req.file.path);if(buf.length<4||buf.subarray(0,2).toString()!=='PK')throw Error('Invalid Excel file.');const wb=XLSX.read(buf,{type:'buffer',cellDates:true});if(!wb.SheetNames.length||wb.SheetNames.length>10)throw Error('Invalid Excel workbook.');const sheet=wb.Sheets[wb.SheetNames[0]],range=XLSX.utils.decode_range(sheet['!ref']||'A1');if(range.e.r>5000||range.e.c>100)throw Error('Workbook exceeds supported size.');const rows=mapped(sheet);let imported=0,updated=0,skipped=0,errors=0;const tx=db.transaction(()=>rows.forEach(x=>{const e=valid(x);if(e){errors++;return}const old=db.prepare('SELECT id FROM shipments WHERE qfz_ref=?').get(x.qfz_ref)as any;if(old){db.prepare(`UPDATE shipments SET ${fields.map(f=>`${f}=?`).join(',')},updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(...fields.map(f=>x[f]),old.id);updated++;}else{db.prepare(`INSERT INTO shipments (${fields.join(',')}) VALUES (${fields.map(()=>'?').join(',')})`).run(...fields.map(f=>x[f]));imported++;}}));tx();fs.unlinkSync(req.file.path);res.json({imported,updated,skipped,errors,total:rows.length,sheet:wb.SheetNames[0]});}catch(e:any){if(req.file&&fs.existsSync(req.file.path))fs.unlinkSync(req.file.path);res.status(400).json({error:'Could not import workbook.'});}});
app.get('/api/export',auth,(_,res)=>{try{const rows=enrichRows(db.prepare('SELECT * FROM shipments ORDER BY id').all() as any[]);const data=rows.map((x:any)=>({'SL NO':x.sl_no,'QFZ Ref':x.qfz_ref,'Packing List':x.packing_list,'Brand':x.brand,'PL Received Date':x.pl_received_date,'PL Received Time':x.pl_received_time,'Metrology Documents Received':x.metrology_documents_received,'Apply for Attestation Date':x.attestation_date,'Apply for Attestation Time':x.attestation_time,'Bayan Received Date':x.bayan_received_date,'Bayan Received Time':x.bayan_received_time,'Payment Confirmation Date':x.payment_confirmation_date,'Payment Confirmation Time':x.payment_confirmation_time,'Metrology Approval Date':x.metrology_approval_date,'Metrology Approval Time':x.metrology_approval_time,'Dispatched Date':x.dispatched_date,'Dispatched Time':x.dispatched_time,'Attestation Duration':x.attestation_duration||'','Total Dispatch Duration':x.total_dispatch_duration||'','Status':x.status,'Attention':x.is_delayed?'Delayed':'','Delay reason':x.delay_reason||'','Remarks':x.remarks}));const ws=XLSX.utils.json_to_sheet(data);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Shipments');const buf=XLSX.write(wb,{type:'buffer',bookType:'xlsx'});res.setHeader('Content-Disposition','attachment; filename="qfz-shipments.xlsx"');res.type('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet').send(buf);}catch{res.status(500).json({error:'Could not export shipments.'});}});
if(process.env.NODE_ENV==='production'){app.use(express.static(path.join(root,'dist')));app.get('*',(_,res)=>res.sendFile(path.join(root,'dist','index.html')))}
app.use((err:any,_:express.Request,res:express.Response,_next:express.NextFunction)=>{if(err instanceof multer.MulterError)return res.status(400).json({error:err.code==='LIMIT_FILE_SIZE'?'Excel file must be 5 MB or smaller.':'Invalid file upload.'});res.status(400).json({error:'Invalid request.'});});
app.listen(Number(process.env.PORT)||3001,'0.0.0.0',()=>console.log('QFZ server running on port '+(process.env.PORT||3001)));
